[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "msd-flow"
version = "0.1.0"
description = "Flow matching framework for galaxy image generation"
requires-python = ">=3.10"
dependencies = [
    "jax==0.6.2",
    "equinox",
    "optax",
    "diffrax",
    "hydra-core",
    "hydra-submitit-launcher",
    "omegaconf",
    "torch",
    "torchvision",
    "numpy<2.0.0",
    "scipy",
    "pandas",
    "astropy",
    "h5py",
    "clearml",
    "tqdm",
    "fastdigest",
    "requests",
    "matplotlib",
    "seaborn",
    "timm",
    "flax>=0.10.0, <0.12.0",
    "orbax-checkpoint",
    "cmasher",
    "scikit-learn"
]

[project.optional-dependencies]
gpu-local = [
  "jax-cuda12-plugin==0.6.2",
  "nvidia-cuda-nvcc-cu12",
]

gpu-bundled = [
  "jax-cuda12-plugin[with-cuda]==0.6.2",
]
docs = ["mkdocs-material", "mkdocs-autorefs"]
dev = ["pytest", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["."]
include = ["msdflow*"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }
