defaults:
  - data@data.download: download_tng50
  - data@data.dataset: dataset
  - data@data.dataloader: dataloader
  - model@model: ncsnpp
  - flow@flow.sample: sample
  - train@train: train
  - clearml@clearml: clearml
  - _self_

seed: 42
image_size: 512
metadata_columns: null # e.g. ["hdr_REDSHIFT"]
work_dir: ${hydra:runtime.cwd}