defaults:
  - data@data.dataloader: mnist_dataloader
  - model@model: unet_mnist
  - flow@flow.sample: sample
  - train@train: train
  - _self_

seed: 42
image_size: 28
metadata_columns: null
work_dir: ${hydra:runtime.cwd}

train:
  checkpoint_dir: ${work_dir}/checkpoints/mnist
  samples_dir: ${work_dir}/samples/mnist
