num_epochs: 100
num_steps_per_epoch: 0
batch_size: 16
checkpoint_dir: ${work_dir}/checkpoints
checkpoint_every: 5
log_every: 1
val_every: 1
ema_decay: 0.9999
optimizer:
  _target_: optax.adam
  learning_rate: 1.0e-4
p_uncond: 0.1
