_target_: msdflow.train.trainer.train
_partial_: true
loss_fn:
  _target_: msdflow.train.metrics.flow_matching_loss
  _partial_: true
batch_metrics:
  - _target_: msdflow.train.metrics.flow_matching_loss
    _partial_: true
epoch_metrics:
  - _target_: msdflow.train.metrics.FIDMetric
    accumulators:
      fid_zoobot:
        _target_: msdflow.train.metrics.FIDAccumulator
        encoder:
          _target_: msdflow.model.convnext.build_zoobot_nano
      fid_inception:
        _target_: msdflow.train.metrics.FIDAccumulator
        encoder:
          _target_: msdflow.model.inceptionv3.build_headless_inceptionv3
    generate_fn:
      _target_: msdflow.flow.sample.sample
      _partial_: true
      shape:
        - 1
        - ${image_size}
        - ${image_size}
      solver:
        _target_: diffrax.Euler
      dt0: 0.01
      t0: 0.0
      t1: 1.0
      stepsize_controller:
        _target_: diffrax.ConstantStepSize
    n_samples: null
    gen_batch_size: 64
    n_real: null
num_train_eval_batches: 0
optimizer:
  _target_: optax.adamw
  learning_rate: 1.0e-4
coupling:
  _target_: msdflow.flow.independent_coupling
  _partial_: true
time_sampler:
  _target_: msdflow.flow.sample_time_uniform
  _partial_: true
  t_min: 0.0
  t_max: 1.0
path_sampler:
  _target_: msdflow.flow.sample_path
  _partial_: true
  sigma_0: 0.0
  sigma_1: 0.0
num_epochs: 100
num_steps_per_epoch: 0
p_uncond: "${if_cond: ${metadata_columns}, 0.1, 1.0}"
checkpoint_dir: ${work_dir}/checkpoints
val_every: 1
checkpoint_every: 10
log_every: ${train.val_every}
ema_decay: 0.9999
sample_fn: null
sample_every: 0
num_samples: 4
samples_dir: ${work_dir}/samples
monitor: flow_matching_loss
monitor_mode: min
early_stopping_patience: 10
